### PR TITLE
chore: sort `package.json`

### PR DESCRIPTION
**Pull request by G-Rath**
### Summary

This uses `sort-package-json` to order the contents in a consistent order, which I find helps when looking over the file.

### Pull Request checklist

- [x] ~Add/update test to cover these changes~
- [x] ~Update documentation~
- [x] ~Update CHANGELOG file~

### CODE REVIEW

**Comment by justin808** [comment]
Makes the blame a lot less useful.

Really worth it?

**Comment by G-Rath** [comment]
Yes I think it is - until it's done, then you'll never get the benefit and then afterwards the blame will recover as further changes are made; you can also [`--ignore-rev`](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt) to exclude the sorting revision (you can also create a [`.git-blame-ignore-revs`](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view) to have the GitHub viewer also ignore it, though I typically don't).

For me this falls into the same camp as tools like `prettier`: they'll _always_ add noise to the `git blame` when they're first introduced but that should mean getting them in ASAP rather than not using them all together 🤷

**Comment by justin808** [comment]
@G-Rath add in:

> [.git-blame-ignore-revs](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view) to have the GitHub viewer also ignore it, though I typically don't).

and I'll merge it!

**Comment by G-Rath** [comment]
@justin808 that's not possible since the commit will change when this gets merged - it has to be in a follow up PR

**Comment by justin808** [comment]
@G-Rath OK! go at it with the follow up!

**Pull request merged**
