### PR TITLE
pending v8 changes

### PR DESCRIPTION
**Pull request by justin808**
### Summary

Pending changes for v8

### Pull Request checklist
_Remove this line after checking all the items here. If the item does not apply to the PR, both check it out and wrap it by `~`._

- [ ] Add/update test to cover these changes
- [ ] Update documentation
- [ ] Update CHANGELOG file

### Other Information

_Remove this paragraph and mention other important and relevant information, such as benchmarks._

### CODE REVIEW

**Comment by Judahmeek** [comment]
@tomdracz Is there any checklist or roadmap for v8?

@ahangarha & I would like to know how we can best assist.

**Comment by G-Rath** [comment]
I was thinking of that, but I think we're almost finished - #430 is the only remaining breaking change we definitely want to land; a potential outcome of #403 is a breaking change that could also be included but I don't think it's clear what the right path to actually take is and it doesn't seem critical given the lack of "+1s" so I don't think we _need_ to get it resolved before releasing v8.

Outside of that the only other questions to consider is what other versions do we want to drop support for - so far we've dropped support for Ruby v2.6 and Node v12.

I don't know of any major pain or things being missed out on by supporting Ruby v2.7 and Node v14 besides just not being able to update some dependencies like Rubocop further meaning we're missing out on a few new rules that are nice to haves.

(being on Ruby 3.1 would let us use shorthand hash properties which is nice, but I think v3.0 is still pretty new enough).

**Comment by tomdracz** [comment]
No checklist/roadmap per se age mostly what outlined above by @G-Rath 

From my perspective we've got plenty of new things, deprecation and fixes to warrant next release.

I'd quite like get all the PRS in flight over the line, though #403 as mentioned elsewhere seems to be need bit more.

I'd also like https://github.com/shakacode/shakapacker/issues/151 to be revisited so could be good to look at alongside existing PRs @Judahmeek @ahangarha

**Comment by G-Rath** [comment]
@tomdracz @ahangarha FYI CI won't run until the merge conflict introduced by #449 is resolved

**Comment by ahangarha** [comment]
@G-Rath What is preventing the conflict resolution?

The changes in #449 are related to v7.2.3, and the changes here are related to the upcoming v8. So the conflict should be easy to resolve.

Are there any specific concerns that I am not aware of?

**Comment by G-Rath** [comment]
@ahangarha I can't resolve the conflict because I'm not a member and you ideally need to push directly to the `next` branch (technically you could do a PR of a merge commit but that is usually very messy)

**Comment by ahangarha** [comment]
@G-Rath Surly I can do this. I need a green light 🟢 to ensure nobody relies on the current `next` branch.

**Comment by G-Rath** [comment]
@ahangarha yup go for it - the only PR open against `next` is mine and I can rebase that easy

**Comment by Judahmeek** [comment]
@ahangarha Can you create documentation similar to [docs/v7_upgrade.md](https://github.com/shakacode/shakapacker/blob/main/docs/v7_upgrade.md) for the v8 upgrade?

If not, let me know so that I can prioritize doing so.

**Comment by justin808** [comment]
> > @ahangarha Can you create documentation similar to [docs/v7_upgrade.md](https://github.com/shakacode/shakapacker/blob/main/docs/v7_upgrade.md) for the v8 upgrade?
> > If not, let me know so that I can prioritize doing so.
> 
> Upgrade guide draft started in #456

I suggest not depending on @ahangarha unless he lets us know otherwise.

**Comment by G-Rath** [comment]
Just to close the loop, I did the upgrade guide in https://github.com/shakacode/shakapacker/pull/458 - so that's good to go.

**Comment by G-Rath** [comment]
@tomdracz @justin808 unless you want to drop more versions of Node or Ruby, I think this major is good to go! Let me know if there's anything else I can do to help get it out the door 🙂

**Comment by justin808** [comment]
Should the beta release be after merging to main?

**Pull request merged**
