### PR TITLE
Fix WEBPACKER_PRECOMPILE value symmetry and improve test coverage

### PR DESCRIPTION
**Pull request by ur5us**

### CODE REVIEW

**Comment by ur5us** [comment]
I’ve marked this PR as draft for now as I don’t actually like the way I test the various true-ish/false-ish values. I think it’d be best to extract them as into private methods and test accepted string values there.

**Comment by ur5us** [comment]
@tomdracz Any thoughts? Otherwise I’ll proceed with my suggestion and finish it off in the next few days.

**Review by justin808 — APPROVED** [review]
LGTM.

**Comment by tomdracz** [comment]
@ur5us Sorry for the delay, been out and about. LGTM, let me know if you want to make any refactors before shipping

**Comment by ur5us** [comment]
@tomdracz Ha, I ended up being out and about quite a bit also. Given that @justin808 merged this as is I wonder whether it still makes sense to refactor a bit. I’m ok either way.

**Comment by justin808** [comment]
@ur5us for sure, make a followup PR if you like.

**Pull request merged**
