### PR TITLE
Safe to bump rspec-rails v6.

### PR DESCRIPTION
**Pull request by Eric-Guo**
### Summary

Just bump the spec-rails

### Pull Request checklist

- [~] Add/update test to cover these changes
- [~] Update documentation
- [~] Update CHANGELOG file

### CODE REVIEW

**Comment by Eric-Guo** [comment]
I can help to testing the v7 version if could release a rc version.

**Comment by ahangarha** [comment]
@Eric-Guo 
> I can help to testing the v7 version if could release a rc version.

It is great. We are waiting working on 2-3 more features to add and then make another rc. Meanwhile, it would be great if you can try Shakapacker 7 using the master branch.

If you have a project with Shakapacker 6, it would be great to check the smoothness of the upgrade process to version 7.

**Review by ahangarha — APPROVED** [review]
Thanks for your contribution 👍🏾

**Comment by ahangarha** [comment]
@justin808 
Should we also include this in version 6?

**Pull request merged**
