### PR TITLE
Clean up duplicated yarn install

### LINKED ISSUE #237: Clean up multiple runs of Yarn install
Related to 
https://github.com/shakacode/shakapacker/pull/131
https://github.com/shakacode/shakapacker/issues/125
https://github.com/shakacode/shakapacker/pull/140

In PR 40, @tomdracz defined `yarn:install` here:
https://github.com/shakacode/shakapacker/pull/140/files#diff-807a4dd8c080e66fff6e78f982df63f6f78b65329a60eb5681fcc941930f435aR5 did

and that redefined the base `yarn:install`

Per https://www.dan-manges.com/blog/modifying-rake-tasks

Redefining ads to the current Rails task `yarn:install`:
https://github.com/rails/rails/blob/7-0-stable/railties/lib/rails/tasks/yarn.rake#L5
https://github.com/rails/rails/blob/6-1-stable/railties/lib/rails/tasks/yarn.rake#L5
https://github.com/rails/rails/blob/5-2-stable/railties/lib/rails/tasks/yarn.rake#L5

And https://github.com/rails/rails/blob/6-1-stable/railties/lib/rails/tasks/yarn.rake#L29

```rb
# Run Yarn prior to Sprockets assets precompilation, so dependencies are available for use.
if Rake::Task.task_defined?("assets:precompile") && File.exist?(Rails.root.join("bin", "yarn"))
  Rake::Task["assets:precompile"].enhance [ "yarn:install" ]
end
```

That causes yarn install to run twice.

Original one removed was webpacker:yarn_install

The current implementation runs yarn install twice always.

# SUMMARY

1. All these yarn installs should be able to turned off as they should be run much earlier in the setup of a production docker image, even for the current shakapacker 6.x.
2. Let's not break the current auto-running of yarn install still run in the case of:
   1. Did not have the assets:precompile yet defined b/c no sprockets
   2. and if has sprockets, allow override to skip enhancing.

So the fix is to remove the duplicate `yarn:install`

### PR DESCRIPTION
**Pull request by justin808**
1. Redefinition of yarn:install caused yarn to run twice ALWAYS as Rails already does trigger a yarn install
2. Removed code no longer needed as Rails 5.2 is the oldest version supported.

Closes #237

### CODE REVIEW

**Review by tomdracz — COMMENTED** [review]
Is this for v7 @justin808 ? I didn't add those files, just restored them. We've originally attempted this in https://github.com/shakacode/shakapacker/pull/131/files

But then I've rolled it back as a response to comments in https://github.com/shakacode/shakapacker/issues/125

Happy with the changes but definitely breaking change for a major release

**Comment by tomdracz** [comment]
But I guess since we're just targeting 5.2 and above it makes sense with the changes that are here. Wondering how long yarn install tak will survive in rails itself though 🤔

**Review by ahangarha — APPROVED** [review]
Looks good to me.
If we don't need to add rest for it, it can be merged.

**Comment by grncdr** [comment]
It seems like 6.5.6 was never published to Rubygems. Is that intentional?

**Comment by ahangarha** [comment]
@grncdr Thanks for sharing this.
There were some concerns. It will be released soon.

**Comment by grncdr** [comment]
No problem, I've found a different workaroudn for my CI, so I'm fine to wait/use a 7.0 beta whenever that's available.

**Comment by januszm** [comment]
this change breaks the CI pipeline in one of my apps that I upgraded from webpacker to shakapacker (Rails 7). Why is it considered redundant? I don't have a separate `yarn install` step in my CI pipeline because until now `assets:precompile` was triggering it. After upgrading shakapacker from 6.5.4 it stopped working.

**Comment by januszm** [comment]
oh, I just noticed this in the source code:

```ruby
if Webpacker.config.webpacker_precompile?
  if Rake::Task.task_defined?("assets:precompile")
    # Rails already adds `yarn install` after 5.2
    # https://github.com/shakacode/shakapacker/issues/237
    enhance_assets_precompile
```

so since version 6.5.5+, to call `yarn install` when compiling assets, do we need to set this option `webpacker_precompile` to true?

**Comment by januszm** [comment]
Honestly, I think this feature should stay (as jsbundling-rails, a solution "competitive/alternative" to shakapacker provides this), but should be controlled with the config option that was present before (webpacker_compile ...), set to false by default

**Pull request merged**
