### PR TITLE
append_javascript_pack_tag helper

### PR DESCRIPTION
**Pull request by tomdracz**
Another stab at improving #39 

Adds new helper to allow providing additional packs in addition that get appended to the main `javascript_pack_tag` call

`javascript_pack_tag` calls still raises when used multiple times but helper can streamline addition of packs in partials or conditionally.

Once we get list of all the tags to output, we deduplicate them and prioritise non-deferred ones - if particular bit is required by both deferred and non deferred call, the non-deferred one will be the one loaded.

Still needs testing and cleanup but just wanted to get initial version out to get thoughts and opinions

cc @justin808

### CODE REVIEW

**Comment by justin808** [comment]
Hi @tomdracz! We need some docs on this.

I like the new API!

```ruby
  def append_javascript_pack_tag(*names, defer: true)
```

This would seem to well handle the cases where the:

1. `javascript_pack_tag` is only on the layout or a partial called from the layout.
2. The layout never calls `append_javascript_pack_tag`. In other words, when the main view (not layout) is rendered, it can call `append_javascript_pack_tag` (and so can any partials called by it as well). But don't try this with partials called by the main view, such as a footer partial.

The tough thing about this API is that there are a few edge cases that are subtle.

How about if we raise if `append_javascript_pack_tag` is called after `javascript_pack_tag`?

**Comment by justin808** [comment]
@tomdracz would be great if we had a full test cases app, as started in #67.

**Comment by tomdracz** [comment]
Thanks @justin808 

> How about if we raise if append_javascript_pack_tag is called after javascript_pack_tag?

Great point! Haven't thought about this but it makes perfect sense.

I'll get this changed, add some docs and see if I can pick up full test app

**Comment by justin808** [comment]
@tomdracz let me know when this is ready for final review!

**Comment by justin808** [comment]
@tomdracz I'm looking forward to this one! big time!

**Comment by tomdracz** [comment]
@justin808 Ready for review!

**Comment by justin808** [comment]
LGTM!

@tomdracz Go ahead and merge if you're confident! 🚀 🚀 🚀 

We really need a sample rails app in the repo for proper tests, like

https://github.com/shakacode/react_on_rails/tree/master/spec/dummy

**Comment by justin808** [comment]
@tomdracz did we address this issue for stylesheets?

**Pull request merged**
