### PR TITLE
fix: support pnpm v9 lockfiles

### PR DESCRIPTION
**Pull request by G-Rath**
### Summary

This was introduced with PNPN v9 and requires a couple of minor changes to support.

### Pull Request checklist

- [x] Add/update test to cover these changes
- [x] ~Update documentation~
- [x] Update CHANGELOG file

### Other Information

Prior art around this: https://github.com/google/osv-scanner/pull/934

## Summary by CodeRabbit

- **New Features**
	- Enhanced version handling to support git-based constraints with pseudo semantic versions.
	- Implemented key format adjustments for versions starting with "v9+".

- **Documentation**
	- Updated lockfile documentation to include new settings for auto-installing peers and excluding links.

- **Tests**
	- Modified test specifications to include additional arguments in `node_package_version` method for comprehensive testing.

### CODE REVIEW

**Comment by G-Rath** [comment]
Note that CI is currently failing due to #470

**Comment by justin808** [comment]
Tests broken. Should we fix first?

```
An error occurred while loading ./spec/system/hello_world_spec.rb.
Failure/Error: require_relative "../config/environment"

RuntimeError:
  **ERROR** Shakapacker: Shakapacker gem and node package versions do not match
  Detected: 7.2.3
       gem: 8.0.0.rc.2
  Ensure the installed version of the gem is the same as the version of
  your installed node package.
  Do not use >= or ~> in your Gemfile for shakapacker without a lockfile.
  Do not use ^ or ~ in your package.json for shakapacker without a lockfile.
```

**Comment by justin808** [comment]
@G-Rath please rebase on main.

**Comment by G-Rath** [comment]
@justin808 done

**Pull request merged**
